/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ForestRouteImport } from './routes/forest'
import { Route as IndexRouteImport } from './routes/index'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ForestRoute = ForestRouteImport.update({
  id: '/forest',
  path: '/forest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forest': typeof ForestRoute
  '/tasks': typeof TasksRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forest': typeof ForestRoute
  '/tasks': typeof TasksRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forest': typeof ForestRoute
  '/tasks': typeof TasksRoute
  '/tree': typeof TreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forest' | '/tasks' | '/tree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forest' | '/tasks' | '/tree'
  id: '__root__' | '/' | '/forest' | '/tasks' | '/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForestRoute: typeof ForestRoute
  TasksRoute: typeof TasksRoute
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forest': {
      id: '/forest'
      path: '/forest'
      fullPath: '/forest'
      preLoaderRoute: typeof ForestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForestRoute: ForestRoute,
  TasksRoute: TasksRoute,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
